import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maria
 */
public class profile extends javax.swing.JFrame 
{
    public String username;
    public profile(String username) {
        
 Connection myconnection;
        this.username= username;
        initComponents();
        //String username1 = getUsernameFromDatabase(username);
        usernamel.setText("Welcome " + username + "!");
         try {
         Class.forName("com.mysql.jdbc.Driver");
                String url ="jdbc:mysql://localhost/touristoffice";
                String user1 = "root";
                String password1 = "";
                myconnection = DriverManager.getConnection(url,user1,password1);
                if (myconnection != null)
                System.out.println("Connected to the database touristoffice");
                Statement stm=myconnection.createStatement();
                ResultSet rs = stm.executeQuery("select username from customers");
               // return username;
        } catch(Exception e)
            {
                System.out.println("e");
            }
    }           

    
    /**
     * Creates new form profile
     */
    public profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        usernamel = new javax.swing.JLabel();
        log_out = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        tips = new javax.swing.JMenu();
        reservation = new javax.swing.JMenu();
        about_us = new javax.swing.JMenu();
        FAQ = new javax.swing.JMenu();
        profile = new javax.swing.JMenu();

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("                                                                       \n\n1. Πώς μπορώ να κάνω κράτηση αεροπορικού εισιτηρίου;\n\nΓια να κάνετε κράτηση αεροπορικού εισιτηρίου, πρέπει πρώτα να είστε συνδεδεμένοι στον λογαριασμό σας. \nΕάν δεν έχετε λογαριασμό, μπορείτε να δημιουργήσετε έναν εύκολα και γρήγορα. Αφού συνδεθείτε, πλοηγηθείτε \nστη σελίδα κρατήσεων και ακολουθήστε τα βήματα για να επιλέξετε τις προτιμώμενες σας επιλογές.\n\n2.  Πώς μπορώ να επιλέξω πιο εύκολα τον προορισμό μου;\n\nΣτην ιστοσελίδα μας, έχουμε δημιουργήσει μια ενότητα με χρήσιμες συμβουλές για την επιλογή του ιδανικού προορισμού. \nΕξερευνήστε τη σελίδα μας με τις \"Συμβουλές\" για να ανακαλύψετε προτάσεις, πληροφορίες για δημοφιλείς\nπροορισμούς και τις τελευταίες τάσεις ταξιδιού. Αυτό θα σας βοηθήσει να καταλήξετε σε μια ενδιαφέρουσα και\nπροσαρμοσμένη επιλογή για το επόμενο ταξίδι σας.\n\n3. Πώς μπορώ να πληρώσω για την κράτησή μου;\n\nΗ πληρωμή για τις κρατήσεις σας γίνεται εύκολα και ασφαλώς μέσω διαθέσιμων επιλογών πληρωμής. Κατά τη διάρκεια της\nδιαδικασίας κράτησης, θα σας προσφέρουμε διάφορες επιλογές πληρωμής, όπως πιστωτικές κάρτες, PayPal και άλλες\nασφαλείς μεθόδους.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Συχνές Ερωτήσεις (FAQ)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        usernamel.setForeground(new java.awt.Color(102, 0, 0));
        usernamel.setText("jLabel3");

        log_out.setText("Log out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(usernamel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(usernamel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        tips.setText("Προτάσεις");
        tips.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipsMouseClicked(evt);
            }
        });
        jMenuBar1.add(tips);

        reservation.setText("Κρατήσεις");
        reservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationMouseClicked(evt);
            }
        });
        jMenuBar1.add(reservation);

        about_us.setText("Σχετικά με εμάς");
        about_us.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about_usMouseClicked(evt);
            }
        });
        jMenuBar1.add(about_us);

        FAQ.setText("FAQ");
        FAQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FAQMouseClicked(evt);
            }
        });
        jMenuBar1.add(FAQ);

        profile.setText("Profile");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        jMenuBar1.add(profile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "You have to register or login");
                reservation r1 = new reservation();
                r1.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_reservationMouseClicked

    private void tipsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipsMouseClicked
        // TODO add your handling code here:
        suggestion s1 = new suggestion();
        s1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tipsMouseClicked

    private void about_usMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_usMouseClicked
        // TODO add your handling code here:
        about_us a1 = new about_us();
        a1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_about_usMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profileMouseClicked

    private void FAQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FAQMouseClicked
        // TODO add your handling code here:
        FAQ f1 = new FAQ();
        f1.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_FAQMouseClicked

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        // TODO add your handling code here:
        JFrame frame=new JFrame("EXIT");
       if(JOptionPane.showConfirmDialog(frame,"Υou want to logout "+username+"?", "EXIT", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
      {
          System.exit(0);
       }
    }//GEN-LAST:event_log_outActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            String username = "Maria"; // Αντικαταστήστε με το όνομα του συνδεδεμένου χρήστη
            new profile(username).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FAQ;
    private javax.swing.JMenu about_us;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton log_out;
    private javax.swing.JMenu profile;
    private javax.swing.JMenu reservation;
    private javax.swing.JMenu tips;
    private javax.swing.JLabel usernamel;
    // End of variables declaration//GEN-END:variables
}
