
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Μαρία
 */
public class suggestion extends javax.swing.JFrame {

    /**
     * Creates new form suggestion
     */
    public suggestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        suggestion = new javax.swing.JMenu();
        reservation = new javax.swing.JMenu();
        about_us = new javax.swing.JMenu();
        FAQ = new javax.swing.JMenu();
        profile = new javax.swing.JMenu();

        jLabel5.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://www.pronews.gr/wp-content/uploads/2014/06/26/brazil_8.jpg")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel5.setText("jLabel1");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(204, 102, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("1) Κωνσταντινούπολη:\n\n*Η ιστορική πόλη που ενώνει την Ασία και την Ευρώπη.\n*Η Σοφία, η Μπλε Τζαμία, και το Κάστρο του Tοπκαπί είναι μερικά από τα κύρια αξιοθέατα.\n*Η γαστρονομία και η νυχτερινή ζωή είναι εξαιρετικές.\n\n2)Καππαδοκία:\n\n*Φημισμένη για τους πανέμορφους βράχους και τις σπηλιές της.\n*Τα αέρινα αγάλματα της φύσης στο Göreme National Park είναι εντυπωσιακά.\n*Το άνω και κάτω Αβσαλόν είναι χωριά με παραδοσιακή αρχιτεκτονική.\n\n3)Αντάλια:\n\n*Μια όμορφη παραθαλάσσια πόλη με λευκά κτίρια και καταγάλανα νερά.\n*Η παραλία Κλεοπάτρας είναι εκπληκτική με λευκή άμμο.\n*Τα αρχαιολογικά τοπία του Ασπενδούς και του Περγάμου είναι ενδιαφέροντα.\n\n4)Παμφυλία:\n\n*Μια περιοχή με φανταστικά τοπία, όπως το Φαράγγι του Σάκλικεντζε και το Φαράγγι του Γκέυτσιν.\n*Η πόλη Αντάνια είναι γνωστή για τα αρχαία χαμάμ και την πολιτιστική κληρονομιά.\n*Το Στόμα του Ακσού, όπου ο ποταμός συναντά τη θάλασσα, είναι μια εκπληκτική τοποθεσία.");
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.pariscityvision.com/library/image/5492.jpg")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("1) Ρίο ντε Τζανέιρο:\n*Φημισμένο για τις παραλίες του, όπως η Copacabana και η Ipanema.\n*Το Σαν Χριστόφορο, με το εμβληματικό Σταυρό του Κορκοβάνα.\n*Το Καρναβάλι της Ρίο, ένα από τα μεγαλύτερα και διάσημα καρναβάλια στον κόσμο.\n\n2) Σάο Πάολο:\n*Η μεγαλύτερη πόλη της Βραζιλίας με δυναμική πολιτιστική σκηνή και εξαιρετική νυχτερινή ζωή.\n*Το Μουσείο Τέχνης της Σάο Πάολο (MASP) είναι ένα από τα σημαντικότερα μουσεία της Λατινικής Αμερικής.\n\n3) Ιγκουασού:\n*Οι καταρράκτες Ιγκουασού, που βρίσκονται στα σύνορα μεταξύ Βραζιλίας και Αργεντινής, είναι μια από τις εντυπωσιακότερες φυσικές ομορφιές του κόμσου.\n\n4) Σαλβαδόρ:\n*Η πρωτεύουσα του Βραζιλιάνικου κράτους της Μπαχίας, γνωστή για το ιστορικό της κέντρο, το Pelourinho.\n*Οι παραλίες της, όπως η Porto da Barra, είναι εξαιρετικές για χαλάρωση.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Προτάσεις προορισμών");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Τουρκία");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Βραζιλία");

        jLabel6.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://travellatino.gr/wp-content/uploads/2017/07/brazil.jpg")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel6.setText("jLabel1");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Γαλλία");

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(153, 102, 0));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("1) Παρίσι:\n*Η πρωτεύουσα της Γαλλίας, γνωστή για τον Πύργο του Άιφελ, τον Λούβρο, το Παρίσι Σαιν-Ζερμέν, και το Μουσείο Ορσέ.\n*Οι λεωφόροι, οι κήποι, και ο ρομαντικός ποταμός Σηκουάνα καθιστούν την πόλη μοναδική.\n\n2) Λυών:\n*Γνωστή ως \"Η Πόλη των Φώτων,\" η Λυών προσφέρει εκλεπτυσμένη αρχιτεκτονική και καταπληκτική γαστρονομία.\n*Ο καθεδρικός ναός του Σαιν-Ζαν-Βατίστ και τα Τρικόρντ Επτά Ράτσια είναι αξιοθέατα.\n\n3) Νίκαια:\n*Τοποθετημένη στη Ριβιέρα της Γαλλίας, η Νίκαια προσφέρει όμορφες παραλίες και λαμπερή νυχτερινή ζωή.\n*Το Προμενάντ και το Μουσείο Μασσηλία είναι κορυφαία αξιοθέατα.\n\n4) Βερσαλλίες:\n*Γνωστή για το Παλάτι της Βερσαλλίας, ένα από τα μεγαλύτερα παλάτια στον κόσμο.\n*Οι καταπράσινοι κήποι και οι πλούσιες αρχιτεκτονικές λεπτομέρειες καθιστούν την περιοχή εντυπωσιακή.");
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(204, 102, 0));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("1) Κωνσταντινούπολη:\n*Η ιστορική πόλη που ενώνει την Ασία και την Ευρώπη.\n*Η Σοφία, η Μπλε Τζαμία, και το Κάστρο του Tοπκαπί είναι μερικά από τα κύρια αξιοθέατα.\n*Η γαστρονομία και η νυχτερινή ζωή είναι εξαιρετικές.\n\n2)Καππαδοκία:\n*Φημισμένη για τους πανέμορφους βράχους και τις σπηλιές της.\n*Τα αέρινα αγάλματα της φύσης στο Göreme National Park είναι εντυπωσιακά.\n*Το άνω και κάτω Αβσαλόν είναι χωριά με παραδοσιακή αρχιτεκτονική.\n\n3)Αντάλια:\n*Μια όμορφη παραθαλάσσια πόλη με λευκά κτίρια και καταγάλανα νερά.\n*Η παραλία Κλεοπάτρας είναι εκπληκτική με λευκή άμμο.\n*Τα αρχαιολογικά τοπία του Ασπενδούς και του Περγάμου είναι ενδιαφέροντα.\n\n4)Παμφυλία:\n*Μια περιοχή με φανταστικά τοπία, όπως το Φαράγγι του Σάκλικεντζε και το Φαράγγι του Γκέυτσιν.\n*Η πόλη Αντάνια είναι γνωστή για τα αρχαία χαμάμ και την πολιτιστική κληρονομιά.\n*Το Στόμα του Ακσού, όπου ο ποταμός συναντά τη θάλασσα, είναι μια εκπληκτική τοποθεσία.");
        jScrollPane4.setViewportView(jTextArea4);

        jLabel8.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://www.travelstyle.gr/wp-content/uploads/2016/09/cappadokia-turkey-guide-travelstylegr.jpg")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel8.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        suggestion.setText("Προτάσεις");
        jMenuBar1.add(suggestion);

        reservation.setText("Κρατήσεις");
        reservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationMouseClicked(evt);
            }
        });
        jMenuBar1.add(reservation);

        about_us.setText("Σχετικά με εμάς");
        about_us.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about_usMouseClicked(evt);
            }
        });
        jMenuBar1.add(about_us);

        FAQ.setText("FAQ");
        FAQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FAQMouseClicked(evt);
            }
        });
        jMenuBar1.add(FAQ);

        profile.setText("Profile");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        jMenuBar1.add(profile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "You have to register or login");
        reservation res1=new reservation();
        res1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reservationMouseClicked

    private void about_usMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_usMouseClicked
        // TODO add your handling code here:
        about_us ab1=new about_us();
        ab1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_about_usMouseClicked

    private void FAQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FAQMouseClicked
        // TODO add your handling code here:
        FAQ FAQ1=new FAQ();
        FAQ1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FAQMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
        profile p1 = new profile();
        p1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_profileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suggestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FAQ;
    private javax.swing.JMenu about_us;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JMenu profile;
    private javax.swing.JMenu reservation;
    private javax.swing.JMenu suggestion;
    // End of variables declaration//GEN-END:variables
}
